export const metadata = {
  title: 'About us',
  description: 'Generated by Next.js',
}

export default function AboutusLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
     
      &copy; Next JS is great!
      {children}
    </div>
  )
}
